[phases.setup]
nixPkgs = ['python310', 'gcc', 'python310Packages.pip', 'python310Packages.setuptools', 'python310Packages.wheel']

[phases.install]
cmds = ['python -m venv /opt/venv && . /opt/venv/bin/activate && pip install --upgrade pip && pip install -r requirements.txt']

[start]
cmd = 'gunicorn app:app'
